### PR TITLE
Enable CC sharing on CI

### PR DESCRIPTION
**Pull request by ZacSweers**
From https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:secrets:configuring_encryption_key

and how androidx does it https://github.com/androidx/androidx/blob/a7f7cfb8087fbcfd117c11c188d69c9a741a17ed/.github/workflows/presubmit.yml#L41

### CODE REVIEW

**Comment by kateliu20** [comment]
Is there a particular reason why we need to encrypt the configuration cache now, or is this a new update that allows this to happen?

**Comment by ZacSweers** [comment]
It was always encrypted before, the change now is that gradle exposed an API to specify the encryption key used. This means that we can share a key that allows us to reuse the cache entries across CI runs, whereas before they were always unique and thus not shareable!

**Review by kateliu20 — APPROVED** [review]
Looks good👍

**Comment by kateliu20** [comment]
> It was always encrypted before, the change now is that gradle exposed an API to specify the encryption key used. This means that we can share a key that allows us to reuse the cache entries across CI runs, whereas before they were always unique and thus not shareable!

That's cool! Would this allow for faster builds then, if the runs can reuse the cache entries now?

**Comment by ZacSweers** [comment]
yep exactly

**Pull request merged**
